# Generated by Django 2.1.3 on 2018-12-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='users_liked',
            field=models.CharField(default=[], max_length=200),
            preserve_default=False,
        ),
    ]
